services:
  devsu-database:
    hostname: postgres-db
    image: lmmdock/postgres-multi
    container_name: devsu-database
    ports:
      - "5432"
    environment:
      POSTGRES_USERS: "devsu_owner:password|devsu_user:password"
      POSTGRES_DATABASES: "devsutecnica_db:devsu_owner"
      POSTGRES_DB: devsutecnica_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    restart: always
#    networks:
 #     - app-network

  #backend:
   # build:
    #  context: ./backend
     # args:
      #  DNS: ${DNS:-localhost}
      #  HTTP_APP_PORT: ${HTTP_APP_PORT:-8083}
    #container_name: spring-backend
    #ports:
     # - "8083:8083"
    #depends_on:
     # - devsu-database
    #networks:
     # - app-network
    #environment:
     # - DATABASE_HOST=devsu-database
      #- DATABASE_PORT=5432

#  frontend:
 #   build:
  #    context: ./frontend
   #   args:
    #    DNS: ${DNS:-localhost}
     #   HTTP_APP_PORT: ${HTTP_APP_PORT:-8080}
  #  container_name: angular-frontend
   # ports:
    #  - "80:80"
 #   depends_on:
  #    - backend
   # networks:
    #  - app-network

#networks:
 # app-network:
  #  driver: bridge