services:
  devsu-database:
    hostname: postgres-db
    image: lmmdock/postgres-multi
    container_name: devsu-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERS: "devsu_owner:password|devsu_user:password"
      POSTGRES_DATABASES: "devsutecnica_db:devsu_owner"
#      POSTGRES_DB: devsutecnica_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devsu_owner -d devsutecnica_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:


#    networks:
 #     - app-network

  app-banco:
    container_name: backend-banco
    build:
      context: ./
      dockerfile: dockerFile
      args:
        DNS: localhost
        HTTP_APP_PORT: 80
    ports:
      - "8083:8083"
    restart: always
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    links:
      - devsu-database
    depends_on:
      devsu-database:
        condition: service_healthy

#  frontend:
 #   build:
  #    context: ./frontend
   #   args:
    #    DNS: ${DNS:-localhost}
     #   HTTP_APP_PORT: ${HTTP_APP_PORT:-8080}
  #  container_name: angular-frontend
   # ports:
    #  - "80:80"
 #   depends_on:
  #    - backend
   # networks:
    #  - app-network

#networks:
 # app-network:
  #  driver: bridge